export type Patient={id:string;firstName:string;lastName:string;mrn:string;dob:string;edd:string;gravida:string;para:string;referringOb:string;obPractice:string;site:string;phone:string;language:string;heightFeet:number;heightInches:number;preWeight:number;currentWeight:number;pregnancyType:string;classification:"A1GDM"|"A2GDM"|"Pending";therapy:string;diagnosisDate:string;notes:string;nextFollowUp:string;status:string;archived:boolean;mock?:boolean;diagnosisTiming?:string;allergies?:string};
export type Reading={id:string;patientId:string;date:string;fasting:number|null;breakfast:number|null;lunch:number|null;dinner:number|null;notes:string};
export type Medication={id:string;patientId:string;name:string;type:string;dose:string;frequency:string;startDate:string;stopDate?:string;status:"Active"|"Discontinued";associatedVisitId?:string;history:string[];breakfastDose?:string;lunchDose?:string;dinnerDose?:string;bedtimeDose?:string;units?:string};
export type MedicationRegimen={medication:string;dose:string;units:string;timing:string};
export type VisitVersion={version:number;finalizedAt:string;provider:string;revisionReason:string;revisionNotes?:string;editedBy?:string;editStartedAt?:string;originalFinalizedAt:string;snapshot:string};
export type Visit={id:string;patientId:string;date:string;type:string;gestationalAge:string;classification:string;control:string;provider:string;status:"Draft"|"Finalized"|"Amended"|"Editing Finalized Visit"|"Refinalized";intervalHistory:string;maternalFindings:string;assessment:string;plan:string;medicationChanges:string;followUp:string;nextFollowUp:string;summary:string;currentTherapy?:string;currentMedication?:MedicationRegimen;newMedication?:MedicationRegimen;bloodPressure?:string;heartRate?:string;edema?:string;glucosePeriod?:string;glucoseStart?:string;glucoseEnd?:string;glucoseReviewDate?:string;dietAdherence?:string;activity?:string;visitModality?:string;smbgAdherence?:string;dietFactors?:string[];activityFrequency?:string;symptoms?:string[];barriers?:string[];education?:string[];educationNotes?:string;fundalHeight?:string;fetalSurveillance?:string;deliveryPlanning?:string;weight?:number;priorWeight?:number;originalNote?:string;amendments?:{date:string;text:string;amendedBy?:string;reason?:string}[];version?:number;finalizedAt?:string;originalFinalizedAt?:string;finalizedBy?:string;editStartedAt?:string;editedBy?:string;revisionReason?:string;revisionNotes?:string;versions?:VisitVersion[];glucoseSnapshot?:Reading[]};
export type ClinicalSummaryData={visitKind:"Initial"|"Follow-Up";gestationalAge:string;classification:string;reason:string;therapy:string;reviewPeriod:string;pattern:string;fasting:string;breakfast:string;lunch:string;dinner:string;overallControl:string;impression:string;plan:string[];medicationChange:string;nextFollowUp:string};
export type ReportSnapshot={patient:Patient;visit?:Visit;readings:Reading[];medications:Medication[];settings:Settings;generatedAt:string;clinicalSummary?:ClinicalSummaryData;schemaVersion?:number};
export type Report={id:string;patientId:string;visitId?:string;visitVersion?:number;date:string;type:string;status:string;generatedBy?:string;fileName?:string;snapshot?:ReportSnapshot};
export type Settings={providerName:string;credentials:string;displayName:string;role:string;practice:string;npi:string;phone:string;fax:string;signature?:string;fastingTarget:number;oneHourTarget:number;twoHourTarget:number;monitoring:"1 hour"|"2 hour";sites:string;defaultFollowUp:string};
export type AppData={patients:Patient[];readings:Reading[];medications:Medication[];visits:Visit[];reports:Report[];settings:Settings};

const days=(n:number)=>{const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const readingSet=(patientId:string,pattern:"fasting"|"dinner"|"goal")=>Array.from({length:7},(_,i)=>{const date=days(i-6);const base=pattern==="fasting"?[98,96,92,99,98,94,96]:pattern==="dinner"?[90,91,93,92,94,91,92]:[87,90,91,89,93,88,90];const dinner=pattern==="dinner"?[146,137,149,142,135,148,139]:pattern==="goal"?[124,130,128,132,126,129,131]:[132,138,142,136,145,137,139];return{id:`${patientId}-r${i}`,patientId,date,fasting:base[i],breakfast:124+i,lunch:118+i,dinner:dinner[i],notes:i===2&&pattern!=="goal"?"Meal timing discussed":""}});
const initialSampleReadings=Array.from({length:6},(_,i)=>({id:`p-sarah-r${i}`,patientId:"p-sarah",date:days(i-5),fasting:[90,91,92,93,94,96][i],breakfast:[118,122,126,120,124,128][i],lunch:[121,125,119,127,123,129][i],dinner:[128,132,134,129,136,131][i],notes:i===5?"Fictional sample reading":""}));
export const demoData:AppData={
 settings:{providerName:"Daniel Riboh",credentials:"PA-C",displayName:"Daniel Riboh, PA-C",role:"GDM Management",practice:"",npi:"",phone:"",fax:"",fastingTarget:95,oneHourTarget:140,twoHourTarget:120,monitoring:"1 hour",sites:"Main Clinic",defaultFollowUp:"1 week"},
 patients:[
  {id:"p-sarah",firstName:"Sarah",lastName:"Cohen",mrn:"DEMO-001",dob:"1993-05-12",edd:"2026-10-21",gravida:"2",para:"1001",referringOb:"Dr. Elena Martinez",obPractice:"Women’s Health Associates",site:"Main Clinic",phone:"(555) 010-1001",language:"English",heightFeet:5,heightInches:5,preWeight:148,currentWeight:162,pregnancyType:"Singleton",classification:"A1GDM",therapy:"Diet controlled",diagnosisDate:"2026-07-28",notes:"Fictional demonstration record.",nextFollowUp:days(7),status:"NEEDS REVIEW",archived:false,mock:true},
  {id:"p-rebecca",firstName:"Rebecca",lastName:"Levy",mrn:"DEMO-002",dob:"1989-11-03",edd:"2026-09-28",gravida:"3",para:"2002",referringOb:"Dr. Priya Shah",obPractice:"Pacific OB/GYN",site:"Main Clinic",phone:"(555) 010-1002",language:"English",heightFeet:5,heightInches:4,preWeight:156,currentWeight:171,pregnancyType:"Singleton",classification:"A2GDM",therapy:"Bedtime insulin",diagnosisDate:"2026-06-30",notes:"Fictional demonstration record.",nextFollowUp:days(3),status:"FOLLOW-UP DUE",archived:false,mock:true},
  {id:"p-miriam",firstName:"Miriam",lastName:"Gold",mrn:"DEMO-003",dob:"1996-02-18",edd:"2026-11-12",gravida:"1",para:"0",referringOb:"Dr. Lauren Kim",obPractice:"Northside Women’s Center",site:"North Clinic",phone:"(555) 010-1003",language:"English",heightFeet:5,heightInches:7,preWeight:139,currentWeight:151,pregnancyType:"Singleton",classification:"A1GDM",therapy:"Diet controlled",diagnosisDate:"2026-08-01",notes:"Fictional demonstration record.",nextFollowUp:days(14),status:"AT GOAL",archived:false,mock:true}
 ],
 readings:[...initialSampleReadings,...readingSet("p-rebecca","fasting"),...readingSet("p-miriam","goal")],
 medications:[{id:"m-rebecca-1",patientId:"p-rebecca",name:"Basaglar",type:"Long acting",dose:"5",units:"units",frequency:"QHS",bedtimeDose:"5",startDate:"2026-07-20",status:"Active",associatedVisitId:"v-rebecca-1",history:["Started manually at documented visit"]}],
 visits:[
  {id:"v-sarah-1",patientId:"p-sarah",date:days(-1),type:"Initial GDM Consultation",gestationalAge:"",classification:"A1GDM",control:"At goal",provider:"Daniel Riboh, PA-C",status:"Finalized",intervalHistory:"Initial consultation and glucose review.",maternalFindings:"Well appearing.",assessment:"A1GDM with glucose values predominantly at goal.",plan:"Continue nutrition therapy and monitoring.",medicationChanges:"None",followUp:"1 week",nextFollowUp:days(7),summary:"GDM education completed. Diet and glucose monitoring plan established.",currentTherapy:"Diet controlled",weight:162,bloodPressure:"118/76",heartRate:"78",edema:"None",version:1,finalizedAt:"2026-08-22T16:15:00.000Z",originalNote:"GDM education completed. Diet and glucose monitoring plan established."},
  {id:"v-rebecca-1",patientId:"p-rebecca",date:days(-1),type:"Follow-Up",gestationalAge:"",classification:"A2GDM",control:"Needs review",provider:"Daniel Riboh, PA-C",status:"Finalized",intervalHistory:"Persistent fasting elevations reviewed.",maternalFindings:"Stable.",assessment:"A2GDM with persistent fasting hyperglycemia; postprandial values predominantly at goal.",plan:"Continue fasting and postprandial monitoring; Increase documented bedtime insulin regimen; Reinforce carbohydrate distribution and post-meal activity; Review glucose log in 1 week",medicationChanges:"Increase Basaglar to 7 units QHS",currentTherapy:"Insulin",currentMedication:{medication:"Basaglar",dose:"5",units:"units",timing:"QHS"},newMedication:{medication:"Basaglar",dose:"7",units:"units",timing:"QHS"},followUp:"1 week",nextFollowUp:days(7),summary:"Bedtime insulin regimen and persistent fasting readings reviewed.",weight:171,bloodPressure:"120/78",heartRate:"80",edema:"None",version:1,finalizedAt:"2026-08-22T17:30:00.000Z",originalNote:"Bedtime insulin regimen and persistent fasting readings reviewed."}
 ],
 reports:[{id:"rep-sarah-1",patientId:"p-sarah",visitId:"v-sarah-1",date:days(-7),type:"GDM Management Report",status:"Final"}]
};

export const newId=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
export const fullName=(p:Patient)=>`${p.firstName} ${p.lastName}`;
