import assert from "node:assert/strict";
import test from "node:test";
import {buildReportModel,maternalLine,validateVisitConsistency} from "../app/lib/reportModel.ts";
import type {Medication,Patient,Reading,Settings,Visit} from "../app/lib/data.ts";

const settings:Settings={providerName:"Daniel Riboh",credentials:"PA-C",displayName:"Daniel Riboh, PA-C",role:"GDM Management",practice:"",npi:"",phone:"",fax:"",fastingTarget:95,oneHourTarget:140,twoHourTarget:120,monitoring:"1 hour",sites:"Main",defaultFollowUp:"1 week"};
const patient:Patient={id:"test-patient",firstName:"Test",lastName:"Patient",mrn:"DEMO-TEST",dob:"1993-05-12",edd:"2026-10-21",gravida:"2",para:"1001",referringOb:"Mock OB",obPractice:"Mock Practice",site:"Mock",phone:"",language:"English",heightFeet:5,heightInches:5,preWeight:125,currentWeight:145,pregnancyType:"Singleton",classification:"A1GDM",therapy:"Diet controlled",diagnosisDate:"2026-07-28",notes:"FICTIONAL",nextFollowUp:"2026-08-30",status:"MOCK",archived:false,mock:true};
const visit:Visit={id:"visit-test",patientId:patient.id,date:"2026-08-17",type:"Initial GDM Consultation",gestationalAge:"18w 3d",classification:"A1GDM",control:"At goal",provider:"Daniel Riboh, PA-C",status:"Finalized",intervalHistory:"Mock visit.",maternalFindings:"Weight 145 lb; BP 119/81; HR 77; edema None; Weight 145 lb; BP 119/81; HR 77; edema None.",assessment:"stale narrative",plan:"Continue nutrition therapy",medicationChanges:"None",followUp:"1 week",nextFollowUp:"2026-08-24",summary:"stale 0/0 text",weight:145,bloodPressure:"119/81",heartRate:"77",edema:"None",version:1,finalizedAt:"2026-08-17T16:15:00.000Z"};
const readings:Reading[]=Array.from({length:6},(_,index)=>({id:`r${index}`,patientId:patient.id,date:`2026-08-${String(10+index).padStart(2,"0")}`,fasting:[90,91,92,93,94,96][index],breakfast:120+index,lunch:121+index,dinner:122+index,notes:""}));

test("A: one report model supplies 1/6 and 17% everywhere",()=>{const model=buildReportModel(patient,visit,readings,[],settings);assert.equal(model.stats.fasting.count,6);assert.equal(model.stats.fasting.above,1);assert.equal(model.stats.fasting.pct,17);assert.match(model.statements.fasting,/1\/6 above goal \(17%\)/);assert.match(model.assessment,/1\/6 above goal \(17%\)/);assert.match(model.summary,/1\/6 above goal \(17%\)/);assert.doesNotMatch(model.summary,/0\/0/)});

test("B: medication titration preserves current and new regimen",()=>{const titration={...visit,type:"Follow-Up",classification:"A2GDM",currentTherapy:"Insulin",currentMedication:{medication:"Basaglar",dose:"5",units:"units",timing:"QHS"},newMedication:{medication:"Basaglar",dose:"7",units:"units",timing:"QHS"},medicationChanges:"Increase Basaglar to 7 units QHS"};const model=buildReportModel({...patient,classification:"A2GDM",therapy:"Insulin"},titration,readings,[],settings);assert.equal(model.currentTherapy,"Basaglar 5 units QHS");assert.equal(model.medicationChange,"Increase Basaglar to 7 units QHS");assert.doesNotMatch(`${model.currentTherapy} ${model.medicationChange} ${model.assessment} ${model.summary}`,/QAM/)});

test("C: gestational age is identical in every generated section",()=>{const model=buildReportModel(patient,visit,readings,[],settings);assert.notEqual(model.gestationalAge,visit.gestationalAge);assert.match(model.assessment,new RegExp(model.gestationalAge));assert.match(model.summary,new RegExp(model.gestationalAge))});

test("D: report finalization flags, signature, and footer are mutually consistent",()=>{const draft=buildReportModel(patient,{...visit,status:"Draft"},readings,[],settings),finalized=buildReportModel(patient,visit,readings,[],settings),revised=buildReportModel(patient,{...visit,status:"Refinalized",version:2,revisionReason:"Corrected documentation"},readings,[],settings);assert.equal(draft.isDraft,true);assert.equal(draft.isFinalized,false);assert.equal(draft.showSignature,false);assert.match(draft.footerText,/Draft/);assert.equal(finalized.isDraft,false);assert.equal(finalized.isFinalized,true);assert.equal(finalized.showSignature,true);assert.doesNotMatch(finalized.footerText,/Draft/);assert.equal(revised.isFinalized,true);assert.equal(revised.isRevised,true);assert.equal(revised.showSignature,true);assert.doesNotMatch(revised.footerText,/Draft/)});

test("E: maternal findings render each measurement once",()=>{const line=maternalLine(patient,visit);for(const token of ["Weight 145 lb","BP 119/81","HR 77","Edema: None"])assert.equal(line.split(token).length-1,1);assert.equal((line.match(/(?:^| · )Weight 145 lb(?: · |$)/g)||[]).length,1)});

test("finalization validation reports material inconsistencies",()=>{const warnings=validateVisitConsistency(patient,{...visit,assessment:"",plan:""},[],[] as Medication[],settings);assert.ok(warnings.some(x=>x.includes("Gestational age")));assert.ok(warnings.some(x=>x.includes("No glucose")));assert.ok(warnings.some(x=>x.includes("Assessment")));assert.ok(warnings.some(x=>x.includes("Plan")));assert.ok(warnings.some(x=>x.includes("duplicated")))});
